### ISSUE TITLE
pinned hyper version dependency conflict with reqwest

### ISSUE THREAD

**Issue by blakehawkins** [slack-rs/slack-rs#70]
The pinned hyper version is `0.9.x` but hyper is now on `0.10.x`.

Would it be easy to fix this up? I have a dependency conflict in my project.

**Comment by dten** [comment]
The websocket crate also wants less than 0.10 so that won't help

**Comment by blakehawkins** [comment]
Here's an open issue for it - https://github.com/cyderize/rust-websocket/issues/95

**Comment by BenTheElder** [comment]
I'll look into this tonight. Hopefully we should be able to resolve this
shortly! Sorry for not responding sooner.

**Comment by BenTheElder** [comment]
If you all can afford to wait, I think the best option is probably to follow what servo does, if not perhaps we can look into migrating to another websocket library.

**Comment by compressed** [comment]
It looks like servo has made their fork: https://github.com/servo/rust-websocket. There's a PR there for updating hyper too.

Although I think we also need to have the underlying `slack_api` crate to move away from hyper too (which looks like is being done in the codegen PR).

**Comment by BenTheElder** [comment]
Thanks for the update. I agree we should probably move everything to
reqwest and the servo websocket fork. The codegen PR and a new release
should be out soon I think.

On Mar 5, 2017 14:31, "compressed" <notifications@github.com> wrote:

It looks like servo has made their fork: https://github.com/servo/rust-
websocket. There's a PR there for updating hyper too.

Although I think we also need to have the underlying slack_api crate to
move away from hyper too (which looks like is being done in the codegen PR).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/slack-rs/slack-rs/issues/70#issuecomment-284253780>,
or mute
the thread

**Comment by blakehawkins** [comment]
Any update on this? I am not following progress on servo's websocket fork

**Comment by compressed** [comment]
@blakehawkins servo's fork is updated to use openssl 0.9 and https://github.com/slack-rs/slack-rs-api is updated to use `reqwest` now. All that's left now is the PR to update this crate.

**Comment by blakehawkins** [comment]
Excellent news! I'm happy to help if there's a pool of simple tasks remaining but it sounds like that's not necessary?

**Comment by compressed** [comment]
I spent some time working on this. There were a lot of changes required. First things first, the servo fork doesn't actually work with `wss://`, only `ws:://`, so that's a non-starter. I considered `ws-rs` but eventually picked [tungstenite](https://github.com/snapview/tungstenite-rs), it supports websocket over TLS and also has a tokio library. I'd really like to see non-blocking `RTMClient`.

Since the the `slack-api` has now changed, we need to swap out `rustc_serialize` for `serde` which also increases the amount of changes. Specifically, the `Event` transformations needed to be reworked. I've only implemented a few (you can check here: https://github.com/compressed/slack-rs/blob/tungstenite/src/events.rs#L271). It seems to be a bit of a pain (i.e. a lot of typing) to match each `Event` variant. Maybe there is a better way; I'm not an expert in serde. Or maybe we could use a macro to make it easier.

You can check out my work here: https://github.com/compressed/slack-rs/tree/tungstenite. I'm open to any help. It's not really in PR form yet given the above... Also not really tested, examples not updated, etc.

**Comment by compressed** [comment]
Update: With some help from the serde experts, I was able to actually have serde generate all the deserialization code for `Event` automatically. I believe the latest code should support all `Event` variants now.

Feel free to check it out and see how it works for you.

Also one note: `reqwest` has an issue (https://github.com/seanmonstar/reqwest/issues/26) that causes it to hang on MacOS at certain times, so I needed to override the `slack-rs-api` `reqwest` impl (see here: https://github.com/slack-rs/slack-rs-api/blob/master/src/requests.rs#L15) to set a `ConnectionClose` header for testing locally.

**Comment by blakehawkins** [comment]
@compressed excellent news. Any further luck with this?

**Comment by blakehawkins** [comment]
I just tested out your version and it works great! In case it's useful at all, here's what I had to change before it would compile:

```
-    fn on_ping(&mut self, cli: &mut slack::RtmClient) {
-        println!("on_ping");
-    }

// post_message API has changed.
-        let _ = cli.post_message("#random", "hello world! (postMessage)", None);

```

**Comment by compressed** [comment]
@blakehawkins great, thanks for the feedback. I still haven't got around to testing it completely myself. I also want to try making slack non-blocking. I'll probably send a PR in the next week or so.

**Comment by dten** [comment]
wondered if in your websocket investigation you had looked at https://github.com/rustyhorde/twist

**Comment by compressed** [comment]
@dten I hadn't heard of it actually. From what I can see though this might be a bit too low level than what's needed for this library. When I started making changes using `tungstenite` it was very straightforward so I just went with that.
